### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by leonlulu** [rkern/line_profiler#106]
I can run the kernprof.py in the terminal. But now I'm using line_profiler package in sumlime-text-3 and when I run the line_profiler on my code I got this permission error in the console:

Running kernprof on /home/liyx/region_class/python_scripts/segmentation.py
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "LineProfiler in /home/liyx/.config/sublime-text-3/Installed Packages/LineProfiler.sublime-package", line 83, in run
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
PermissionError: [Errno 13] Permission denied

I already tried to open sublime in sudo mode and run 'chmod' on the '/opt/sublime_text/python3.3.zip' file, but didn't work. What should I do about it?

Many thanks.

**Comment by caethan** [comment]
Sorry, can't support other products trying to use line profiler
