### ISSUE TITLE
Python3.6 ModuleNotFoundError on Import

### ISSUE THREAD

**Issue by n8henrie** [rkern/line_profiler#110]
```shellsession
$ python3 --version
Python 3.6.3
$ python3 -m pip freeze | grep line-profiler
line-profiler==2.1.1
$ python3 -c 'import line_profiler'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/line_profiler.py", line 68, in <module>
    class LineProfiler(CLineProfiler):
  File "/usr/local/lib/python3.6/site-packages/line_profiler.py", line 122, in LineProfiler
    import line_profiler_py35
ModuleNotFoundError: No module named 'line_profiler_py35'
```

Downgrading to 2.0 imports okay.

OSX 10.13.2

**Comment by n8henrie** [comment]
```shell_session
$ git bisect start HEAD fcdba72ed5f8b62ef86b6bdcf9ef856575032c9f
Bisecting: 8 revisions left to test after this (roughly 3 steps)
[e20658e3aa286dc647fbde34d85d8c39fff9f2eb] Merge pull request #75 from pfreixes/master
$ git bisect run venv/bin/python3 -c 'import line_profiler'
```
....
```
a82d7e30430ab7758c5fb33be89c0bc67e7e4414 is the first bad commit
```

**Comment by n8henrie** [comment]
Doesn't look like that file made it into the tar archive.

```shellsession
$ wget https://pypi.python.org/packages/0f/8b/803471ca150d9247a18726f848f6633d301aba634ed013fd2645d8b16ce5/line_profiler-2.1.1.tar.gz#md5=b4a0d6e1bc11df7560b14870b3858bd8
$ tar xzf line_profiler-2.1.1.tar.gz
$ cd line_profiler-2.1.1/
$ ls
LICENSE.txt         PKG-INFO          _line_profiler.pyx      line_profiler.py  setup.py  timers.h
LICENSE_Python.txt  README.rst        kernprof.py             python25.pxd      tests     unset_trace.c
MANIFEST.in         _line_profiler.c  line_profiler.egg-info  setup.cfg         timers.c  unset_trace.h
```

**Comment by caethan** [comment]
Looks like it's a byproduct of the coroutine support we added - has an additional file that only gets imported in python 3.5 and up, and since I built with 2.7, didn't get added to the tarball.  Thanks for the report, will get this fixed.

**Comment by caethan** [comment]
@n8henrie Can you try the 2.1.2 release I just pushed to PyPI?

**Comment by n8henrie** [comment]
2.1.2 seems to work like a charm, thanks for the quick attention!
