### ISSUE TITLE
Python3.6 ModuleNotFoundError on Import

### ISSUE THREAD

**Issue by Vicentelles** [rkern/line_profiler#122]
$ python3 --version
Python 3.6.5
$ python3 -m pip freeze | grep line-profiler
line-profiler==2.1.2

$ kernprof -l -v backProcessor.py
Wrote profile results to backProcessor.py.lprof
Timer unit: 1e-06 s

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/kernprof", line 11, in <module>
    load_entry_point('line-profiler==2.1.2', 'console_scripts', 'kernprof')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kernprof.py", line 222, in main
    execfile(script_file, ns, ns)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kernprof.py", line 35, in execfile
    exec_(compile(f.read(), filename, 'exec'), globals, locals)
  File "backProcessor.py", line 2, in <module>
    from vrt.level1Processor import processLvl1, setLevelPrices
ModuleNotFoundError: No module named 'vrt'

Installed from pip3

"vrt" is a folder, "vrt.level1Processor" is the module.

It is not being interpreted rightly

Please, I need to use the line profiler. It is very important for my project

**Comment by caethan** [comment]
Looks to me like a pythonpath issue - n.b. that kernprof doesn't automatically assume that the local directory is in your pythonpath.
