### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by AlanMarcon** [rkern/line_profiler#13]
After execute:
alan@ar2:~/Document/$ python -m line_profiler S-SEBI_Orientado.py.lprof 
I got this error:

Function: getEntrada at line 75
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/line_profiler.py", line 394, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/line_profiler.py", line 391, in main
    show_text(lstats.timings, lstats.unit)
  File "/usr/local/lib/python2.7/dist-packages/line_profiler.py", line 227, in show_text
    show_func(fn, lineno, name, stats[fn, lineno, name], unit, stream=stream, stripzeros=stripzeros)
  File "/usr/local/lib/python2.7/dist-packages/line_profiler.py", line 201, in show_func
    '%5.1f' % (100*time / total_time))
ZeroDivisionError: float division by zero

**Comment by kmwenja** [comment]
Got the same thing for like 4 runs then it disappeared. Running the profile script `kernprof -l -v script {args}` in tox 2.3.1.

**Comment by ronbarak** [comment]
I get the same error when I run on the attached code:

$ python -m line_profiler mult_table.py.lprof
Timer unit: 1e-06 s

Total time: 0 s
File: mult_table.py
Function: print_header at line 4
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/line_profiler.py", line 394, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/line_profiler.py", line 391, in main
    show_text(lstats.timings, lstats.unit)
  File "/usr/lib/python2.7/site-packages/line_profiler.py", line 227, in show_text
    show_func(fn, lineno, name, stats[fn, lineno, name], unit, stream=stream, stripzeros=stripzeros)
  File "/usr/lib/python2.7/site-packages/line_profiler.py", line 201, in show_func
    '%5.1f' % (100*time / total_time))
ZeroDivisionError: float division by zero


[mult_table.py.txt](https://github.com/rkern/line_profiler/files/267155/mult_table.py.txt)

**Comment by Nodd** [comment]
I looked at the code, and the only explanation I found is that the lines in your function are executed in less than a timer unit (1e-6s), I don't know how it's possible. On what platform are you ?
