### ISSUE TITLE
pip install line-profiler 3.0.2 fails (python 3.7.4, alpine linux)

### ISSUE THREAD

**Issue by Joeboy** [rkern/line_profiler#177]
Hi. I get this when trying to pip install line-profiler 3.0.2 on alpine linux 3.10.2, python 3.7.5:

```bash-5.0# pip install line-profiler
Looking in indexes: https://pypi.org/simple, http://pypi.wfp.org/simple/
Collecting line-profiler
  Downloading https://files.pythonhosted.org/packages/98/bd/4ff4e59f97897d21b3b7d0c97ac77cedab23e6137a8c8fb3cbc9ee9d1f71/line_profiler-3.0.2.tar.gz (45kB)
     |████████████████████████████████| 51kB 2.2MB/s 
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.7 /usr/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-31sy4dvd/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url http://pypi.wfp.org/simple/ --trusted-host pypi.wfp.org -- 'setuptools>=41.0.1' wheel Cython 'scikit-build>=0.9.0' cmake ninja
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/lib/python3.7/site-packages/pip/__main__.py", line 16, in <module>
      from pip._internal.main import main as _main  # isort:skip # noqa
    File "/usr/lib/python3.7/site-packages/pip/_internal/main.py", line 8, in <module>
      import locale
    File "/usr/lib/python3.7/locale.py", line 16, in <module>
      import re
    File "/usr/lib/python3.7/re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.7 /usr/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-31sy4dvd/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url http://pypi.wfp.org/simple/ --trusted-host pypi.wfp.org -- 'setuptools>=41.0.1' wheel Cython 'scikit-build>=0.9.0' cmake ninja Check the logs for full command output.
bash-5.0#
```

That's with python 3.7.5. FWIW I also tried with python 2.7 and got a different error but I'll leave that for now.

Thanks.

**Comment by rkern** [comment]
Development of the 3.x series has moved to https://github.com/pyutils/line_profiler
