### ISSUE TITLE
AttributeError: 'property' object has no attribute '__code__'

### ISSUE THREAD

**Issue by victorhooi** [rkern/line_profiler#21]
I'm trying to profile the following code:

https://github.com/rueckstiess/mtools/blob/8ee80ac14fa1425cfbdaa7c0c0a2c69f36ecae21/mtools/util/logevent.py

I have added `@profile` to the `duration` method as follows:

```
    @profile
    @property
    def duration(self):
        """ calculate duration if available (lazy) """
```

However, when I run the code via `kernprof`, it gives me the following error:

```
kernprof -l -v mloginfo --queries mongodb.log
/usr/local/lib/python2.7/site-packages/line_profiler.py:62: UserWarning: Could not extract a code object for the object <property object at 0x110181fc8>
  self.add_function(func)
Wrote profile results to mloginfo.lprof
Timer unit: 1e-06 s

Traceback (most recent call last):
  File "/usr/local/bin/kernprof", line 9, in <module>
    load_entry_point('line-profiler==1.0', 'console_scripts', 'kernprof')()
  File "/usr/local/lib/python2.7/site-packages/kernprof.py", line 221, in main
    execfile(script_file, ns, ns)
  File "/usr/local/bin/mloginfo", line 9, in <module>
    load_entry_point('mtools==1.1.8', 'console_scripts', 'mloginfo')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/mtools/mloginfo/mloginfo.py", line 3, in <module>
    from mtools.util.logfile import LogFile
  File "/usr/local/lib/python2.7/site-packages/mtools/util/logfile.py", line 1, in <module>
    from mtools.util.logevent import LogEvent
  File "/usr/local/lib/python2.7/site-packages/mtools/util/logevent.py", line 18, in <module>
    class LogEvent(object):
  File "/usr/local/lib/python2.7/site-packages/mtools/util/logevent.py", line 155, in LogEvent
    @property
  File "/usr/local/lib/python2.7/site-packages/line_profiler.py", line 63, in __call__
    if is_generator(func):
  File "/usr/local/lib/python2.7/site-packages/line_profiler.py", line 50, in is_generator
    isgen = (f.__code__.co_flags & CO_GENERATOR) != 0
AttributeError: 'property' object has no attribute '__code__'
```

Is this to do with the fact it's a method? Or something else?

**Comment by rkern** [comment]
`@profile` needs to be directly adjacent to the method. See #19 

```
@property
@profile
def duration(self):
    ...
```
