### ISSUE TITLE
Simple example failing

### ISSUE THREAD

**Issue by kcrum** [rkern/line_profiler#32]
I have not been able to get line_profiler working. As an example, I tried to do line-by-line profiling of a simple script that finds all prime numbers less than 100. The script is as follows: 

```python
@profile                                                                         
def primes(n):                                                                   
    if n==2:                                                                    
        return [2]                                                              
    elif n<2:                                                                   
        return []                                                                
    s=range(3,n+1,2)                                                            
    mroot = n ** 0.5                                                            
    half=(n+1)/2-1                                                               
    i=0                                                                          
    m=3                                                                          
    while m <= mroot:                                                            
        if s[i]:                                                                 
            j=(m*m-3)/2                                                          
            s[j]=0                                                               
            while j<half:                                                        
                s[j]=0                                                           
                j+=m                                                             
        i=i+1                                                                    
        m=2*i+3                                                                  
    return [2]+[x for x in s if x]                                               
print primes(100)                                                                
```

I get the following error when calling the following in terminal:
```
[kcrum]coding_space/test_code > kernprof -l -v primes.py 
Wrote profile results to primes.py.lprof
Timer unit: 1e-06 s

Traceback (most recent call last):
  File "/usr/local/bin/kernprof", line 9, in <module>
    load_entry_point('line-profiler==1.0', 'console_scripts', 'kernprof')()
  File "/usr/local/lib/python2.7/site-packages/kernprof.py", line 221, in main
    execfile(script_file, ns, ns)
  File "primes.py", line 1, in <module>
    @profile
NameError: name 'profile' is not defined
```

Any help understanding this error would be greatly appreciated. For the record, I'm running python 2.7.9 on a Mac, and I'm running kernprof 1.0b2, which is what pip installed.

**Comment by jan-glx** [comment]
Same for me on Windows 8.1:
Does throw `NameError: name 'profile' is not defined`
under `Python 2.7.10 :: Anaconda 2.3.0 (64-bit)`
but runs fine under `Python 3.3.5 :: Anaconda 2.3.0 (64-bit)`
(even with a more simple example:)
````
@profile
def test():
    return True
test()
````

**Comment by xgdgsc** [comment]
Same here with Python 2.7.10 :: Anaconda 2.3.0 (64-bit) in win 10

**Comment by xgdgsc** [comment]
Already fixed in https://github.com/rkern/line_profiler/pull/25, hope a new version get released to pypi.

**Comment by caethan** [comment]
2.0 released on PyPi with this fix included.
