### ISSUE TITLE
[Ubuntu 14.04] Cannot install - getting: "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 56: ordinal not in range(128)"

### ISSUE THREAD

**Issue by chris-asl** [rkern/line_profiler#36]
I am trying to install line profiler via pip and getting the aforementioned error.  
This is the output of `pip install line_profiler`.  

```
Downloading/unpacking line-profiler
  Downloading line_profiler-1.0.tar.gz (65kB): 65kB downloaded
  Running setup.py (path:/tmp/pip_build_chris/line-profiler/setup.py) egg_info for package line-profiler
    Could not import Cython. Using the available pre-generated C file.
    
Installing collected packages: line-profiler
  Running setup.py install for line-profiler
    Could not import Cython. Using the available pre-generated C file.
    building '_line_profiler' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c _line_profiler.c -o build/temp.linux-x86_64-2.7/_line_profiler.o
    In file included from _line_profiler.c:353:0:
    unset_trace.h:1:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void unset_trace();
     ^
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c timers.c -o build/temp.linux-x86_64-2.7/timers.o
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c unset_trace.c -o build/temp.linux-x86_64-2.7/unset_trace.o
    unset_trace.c:5:6: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void unset_trace() {
          ^
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/_line_profiler.o build/temp.linux-x86_64-2.7/timers.o build/temp.linux-x86_64-2.7/unset_trace.o -o build/lib.linux-x86_64-2.7/_line_profiler.so
    error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/line_profiler.py'
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_chris/line-profiler/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-JtMfZ_-record/install-record.txt --single-version-externally-managed --compile:
    Could not import Cython. Using the available pre-generated C file.

running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

copying line_profiler.py -> build/lib.linux-x86_64-2.7

copying kernprof.py -> build/lib.linux-x86_64-2.7

running build_ext

building '_line_profiler' extension

creating build/temp.linux-x86_64-2.7

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c _line_profiler.c -o build/temp.linux-x86_64-2.7/_line_profiler.o

In file included from _line_profiler.c:353:0:

unset_trace.h:1:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]

 void unset_trace();

 ^

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c timers.c -o build/temp.linux-x86_64-2.7/timers.o

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c unset_trace.c -o build/temp.linux-x86_64-2.7/unset_trace.o

unset_trace.c:5:6: warning: function declaration isn’t a prototype [-Wstrict-prototypes]

 void unset_trace() {

      ^

x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/_line_profiler.o build/temp.linux-x86_64-2.7/timers.o build/temp.linux-x86_64-2.7/unset_trace.o -o build/lib.linux-x86_64-2.7/_line_profiler.so

running install_lib

copying build/lib.linux-x86_64-2.7/line_profiler.py -> /usr/local/lib/python2.7/dist-packages

error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/line_profiler.py'

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_chris/line-profiler/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-JtMfZ_-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_chris/line-profiler
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 56: ordinal not in range(128)
```

**Comment by rkern** [comment]
The underlying problem is this:

```
error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/line_profiler.py'
```

Which you will have to fix on your own. The other error is in `pip` which is getting some non-ASCII-encoded bytes from the build log and mixing them with `unicode` strings somehow.
