### ISSUE TITLE
'profile' is not defined on OS X

### ISSUE THREAD

**Issue by oam31** [rkern/line_profiler#46]
When running kernprof -l -v test.py on the following test.py file:

```
@profile
def test():
    a = 1
    b = 1
    return a + b

if __name__ == '__main__':
    print test()
```
I get:
```
$ kernprof -l -v test.py
Wrote profile results to test.py.lprof
Timer unit: 1e-06 s

Traceback (most recent call last):
  File "/usr/local/bin/kernprof", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/kernprof.py", line 221, in main
    execfile(script_file, ns, ns)
  File "test.py", line 1, in <module>
    @profile
NameError: name 'profile' is not defined
```
This error appears on:
```
OS X El Capitan 10.11.2

Python 2.7.11 (default, Dec  8 2015, 09:38:05)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin

line-profiler (1.0)
```
but not on:
```
Windows 7 SP1
Python 2.7.11 | Anaconda 2.4.0 (64bits)
line-profiler (1.0)
```

WHY ???

Thanks.

**Comment by oam31** [comment]
Sorry, issue #25 solves the problem!
