### ISSUE TITLE
UnicodeDecodeError when displaying timings

### ISSUE THREAD

**Issue by Nodd** [rkern/line_profiler#6]
I often use strings with non-ascii characters, both in code and in documentation (comments or docstrings). When I run line_profiler using ```kernprof -lv myscript.py```, the output prints until the first line with a non-ascii character where I get this error:
```
Traceback (most recent call last):
  File "/usr/bin/kernprof", line 9, in <module>
    load_entry_point('line-profiler==1.0', 'console_scripts', 'kernprof')()
  File "/usr/lib/python2.7/site-packages/kernprof.py", line 230, in main
    prof.print_stats()
  File "/usr/lib/python2.7/site-packages/line_profiler.py", line 117, in print_stats
    show_text(lstats.timings, lstats.unit, stream=stream, stripzeros=stripzeros)
  File "/usr/lib/python2.7/site-packages/line_profiler.py", line 227, in show_text
    show_func(fn, lineno, name, stats[fn, lineno, name], unit, stream=stream, stripzeros=stripzeros)
  File "/usr/lib/python2.7/site-packages/line_profiler.py", line 215, in show_func
    stream.write(txt)
  File "/usr/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 84: ordinal not in range(128)
```
My files are in utf-8, and declared as such using ```# -*- coding: utf-8 -*-```.

**Comment by Nodd** [comment]
This was my fault, I was reencoding sys.stdout for a problem with argparse.
