### ISSUE TITLE
%lprun will break as of IPython 5.0

### ISSUE THREAD

**Issue by anntzer** [rkern/line_profiler#61]
`define_magic` has apparently been deprecated for a while and is now removed: https://github.com/ipython/ipython/pull/9504/files
Starting IPython with the `line_profiler` extension will fail with
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/IPython/core/shellapp.py", line 246, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/usr/lib/python3.5/site-packages/IPython/core/extensions.py", line 85, in load_extension
    if self._call_load_ipython_extension(mod):
  File "/usr/lib/python3.5/site-packages/IPython/core/extensions.py", line 132, in _call_load_ipython_extension
    mod.load_ipython_extension(self.shell)
  File "/usr/lib/python3.5/site-packages/line_profiler.py", line 372, in load_ipython_extension
    ip.define_magic('lprun', magic_lprun)
AttributeError: 'TerminalInteractiveShell' object has no attribute 'define_magic'
```

**Comment by caethan** [comment]
I have a pull request in to fix this: https://github.com/rkern/line_profiler/pull/65

Please try it out and see if it works with your system.

**Comment by anntzer** [comment]
duplicate of #62, and I moved on to using another profiler in the meantime... thanks though.

**Comment by cancan101** [comment]
@anntzer What profiler are you using now?

**Comment by anntzer** [comment]
https://github.com/vpelletier/pprofile
Output in the callgrind format is a killer feature imo...
